apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
data:
  elasticsearch.yml: |
    node.name: single-node
    cluster.name: medeasy-elastic-cluster
    discovery.type: single-node
    network.host: 0.0.0.0
    path.repo: /usr/share/elasticsearch/backup
    xpack.security.enabled: true
    xpack.security.transport.ssl.enabled: false
    xpack.security.http.ssl.enabled: false